spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/sensors_monitor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

server:
  servlet:
    context-path: /sensor
  tomcat:
    uri-encoding: UTF-8
